# Default values for helm-project-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Helm Project Operator Configuration

global:
  cattle:
    clusterId: ""
    projectLabel: field.cattle.io/projectId
    systemDefaultRegistry: ""
    systemProjectId: ""
    url: ""
  rbac:
    ## Create RBAC resources for ServiceAccounts and users
    ##
    create: true

    userRoles:
      ## Create default user ClusterRoles to allow users to interact with ProjectHelmCharts
      create: true
      ## Aggregate default user ClusterRoles into default k8s ClusterRoles
      aggregateToDefaultRoles: true

    pspEnabled: true
    pspAnnotations: {}
      ## Specify pod annotations
      ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#apparmor
      ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp
      ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#sysctl
      ##
      # seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
      # seccomp.security.alpha.kubernetes.io/defaultProfileName: 'docker/default'
      # apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'

  ## Reference to one or more secrets to be used when pulling images
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  imagePullSecrets: []
  # - name: "image-pull-secret"

helmApiVersion: dummy.cattle.io/v1alpha1

## releaseRoleBindings configures RoleBindings automatically created by the Helm Project Operator
## in Project Release Namespaces where underlying Helm charts are deployed
releaseRoleBindings:
  ## aggregate enables creating these RoleBindings off aggregating RoleBindings in the
  ## Project Registration Namespace or ClusterRoleBindings that bind users to the ClusterRoles
  ## specified under clusterRoleRefs
  aggregate: true

  ## clusterRoleRefs are the ClusterRoles whose RoleBinding or ClusterRoleBindings should determine
  ## the RoleBindings created in the Project Release Namespace
  ## 
  ## By default, these are set to create RoleBindings based on the RoleBindings / ClusterRoleBindings
  ## attached to the default K8s user-facing ClusterRoles of admin, edit, and view.
  ## ref: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
  ##
  clusterRoleRefs:
    admin: admin
    edit: edit
    view: view

nameOverride: ""

namespaceOverride: ""

image:
  repository: arvindiyengar/helm-project-operator # TODO: modify to rancher/helm-project-operator
  tag: dev
  pullPolicy: Always # TODO: modify to IfNotPresent

helmcontroller:
  job:
    image:
      repository: rancher/klipper-helm
      tag: v0.7.0-build20220315

# Additional arguments to be passed into the Helm Project Operator image
additionalArgs: []

## Define which Nodes the Pods are scheduled on.
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for use with node taints
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"

resources: {}
  # limits:
  #   memory: 500Mi
  #   cpu: 1000m
  # requests:
  #   memory: 100Mi
  #   cpu: 100m

securityContext: {}
  # allowPrivilegeEscalation: false
  # readOnlyRootFilesystem: true

debug: false
debugLevel: 0

cleanup:
  image:
    repository: rancher/shell
    tag: v0.1.14

  nodeSelector: {}

  tolerations: []
