annotations:
  catalog.cattle.io/auto-install: helm-project-operator-crd=match
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Prometheus Federator
  catalog.cattle.io/kube-version: '>=1.16.0-0'
  catalog.cattle.io/namespace: cattle-monitoring-system
  catalog.cattle.io/os: linux,windows
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: helm.cattle.io.projecthelmchart/v1alpha1
  catalog.cattle.io/rancher-version: '>= 2.6.0-0 <=2.6.99-0'
  catalog.cattle.io/release-name: prometheus-federator
apiVersion: v2
appVersion: 0.0.1
dependencies:
- condition: helmProjectOperator.enabled
  name: helmProjectOperator
  repository: file://./charts/helmProjectOperator
description: Prometheus Federator
name: prometheus-federator
version: 0.0.1
